-- Base de datos siniestrlidad
drop database if exists siniestralidad;
create database siniestralidad;

use siniestralidad

CREATE TABLE tramos
(
    ID	INT primary key auto_increment,
    TRAMO	VARCHAR(512)
);

INSERT INTO tableName (ID, TRAMO) VALUES ('1', 'ACATZINGO - CIUDAD MENDOZA');
INSERT INTO tableName (ID, TRAMO) VALUES ('2', 'ACAYUCAN - COSOLEACAQUE');
INSERT INTO tableName (ID, TRAMO) VALUES ('3', 'AEROPUERTO LOS CABOS - SAN JOSE DEL CABO - CABO SAN LUCAS');
INSERT INTO tableName (ID, TRAMO) VALUES ('4', 'AGUA DULCE - CÁRDENAS');
INSERT INTO tableName (ID, TRAMO) VALUES ('5', 'AMECAMECA - NEPANTLA');
INSERT INTO tableName (ID, TRAMO) VALUES ('6', 'CHAMAPA - LECHERÍA');
INSERT INTO tableName (ID, TRAMO) VALUES ('7', 'CHAMPOTÓN - CAMPECHE');
INSERT INTO tableName (ID, TRAMO) VALUES ('8', 'CHAPALILLA - COMPOSTELA');
INSERT INTO tableName (ID, TRAMO) VALUES ('9', 'CIUDAD MENDOZA - CÓRDOBA');
INSERT INTO tableName (ID, TRAMO) VALUES ('10', 'CÓRDOBA - VERACRUZ');
INSERT INTO tableName (ID, TRAMO) VALUES ('11', 'CUACNOPALAN - OAXACA');
INSERT INTO tableName (ID, TRAMO) VALUES ('12', 'CUERNAVACA - ACAPULCO');
INSERT INTO tableName (ID, TRAMO) VALUES ('13', 'DURANGO - MAZATLÁN');
INSERT INTO tableName (ID, TRAMO) VALUES ('14', 'ENTRONQUE CIUDAD CUAUHTÉMOC - ENTRONQUE OSIRIS');
INSERT INTO tableName (ID, TRAMO) VALUES ('15', 'ESTACIÓN DON - NOGALES');
INSERT INTO tableName (ID, TRAMO) VALUES ('16', 'GÓMEZ PALACIO - CORRALITOS');
INSERT INTO tableName (ID, TRAMO) VALUES ('17', 'GUTIERREZ ZAMORA - TIHUATLÁN');
INSERT INTO tableName (ID, TRAMO) VALUES ('18', 'LA PERA - CUAUTLA');
INSERT INTO tableName (ID, TRAMO) VALUES ('19', 'LA RUMOROSA - TECATE');
INSERT INTO tableName (ID, TRAMO) VALUES ('20', 'LA TINAJA - COSOLEACAQUE');
INSERT INTO tableName (ID, TRAMO) VALUES ('21', 'LAGOS DE MORENO - SAN LUIS POTOSÍ');
INSERT INTO tableName (ID, TRAMO) VALUES ('22', 'LAS CHOAPAS - OCOZOCOAUTLA');
INSERT INTO tableName (ID, TRAMO) VALUES ('23', 'LIBRAMIENTO CUERNAVACA');
INSERT INTO tableName (ID, TRAMO) VALUES ('24', 'LIBRAMIENTO NORESTE DE QUERÉTARO');
INSERT INTO tableName (ID, TRAMO) VALUES ('25', 'LIBRAMIENTO ORIENTE DE SALTILLO');
INSERT INTO tableName (ID, TRAMO) VALUES ('26', 'LIBRAMIENTO PONIENTE DE TAMPICO');
INSERT INTO tableName (ID, TRAMO) VALUES ('27', 'MÉXICO - CUERNAVACA');
INSERT INTO tableName (ID, TRAMO) VALUES ('28', 'MÉXICO - PUEBLA');
INSERT INTO tableName (ID, TRAMO) VALUES ('29', 'MÉXICO - QUERÉTARO');
INSERT INTO tableName (ID, TRAMO) VALUES ('30', 'PUEBLA - ACATZINGO');
INSERT INTO tableName (ID, TRAMO) VALUES ('31', 'PUENTE DE IXTLA - IGUALA');
INSERT INTO tableName (ID, TRAMO) VALUES ('32', 'PUENTE NACIONAL');
INSERT INTO tableName (ID, TRAMO) VALUES ('33', 'PUENTES EL ZACATAL');
INSERT INTO tableName (ID, TRAMO) VALUES ('34', 'PUENTES INTERNACIONALES');
INSERT INTO tableName (ID, TRAMO) VALUES ('35', 'PUENTES NACIONALES');
INSERT INTO tableName (ID, TRAMO) VALUES ('36', 'PUERTO MÉXICO - LA CARBONERA');
INSERT INTO tableName (ID, TRAMO) VALUES ('37', 'QUERÉTARO - IRAPUATO');
INSERT INTO tableName (ID, TRAMO) VALUES ('38', 'RANCHO VIEJO - TAXCO');
INSERT INTO tableName (ID, TRAMO) VALUES ('39', 'SALINA CRUZ - TEHUANTEPEC - LA VENTOSA');
INSERT INTO tableName (ID, TRAMO) VALUES ('40', 'SALTILLO - TORREÓN');
INSERT INTO tableName (ID, TRAMO) VALUES ('41', 'TIJUANA - ENSENADA');

CREATE TABLE caseta
(
    ID	INT,
    NUMERO_CASETA	INT,
    NOMBRE_CASETA	VARCHAR(512)
);

INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('1', '34', 'PLAYAS DE TIJUANA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('2', '35', 'ROSARITO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('3', '36', 'ENSENADA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('4', '83', 'EL HONGO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('5', '189', 'POPOTLA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('6', '148', 'ESTACION DON');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('7', '149', 'FUNDICION');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('8', '150', 'ESPERANZA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('9', '151', 'GUAYMAS');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('10', '152', 'HERMOSILLO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('11', '153', 'MAGDALENA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('12', '40', 'PUENTE NACIONAL CADEREYTA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('13', '140', 'LA CARBONERA (OJO CALIENTE)');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('14', '141', 'LOS CHORROS');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('15', '160', 'BERMEJILLO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('16', '161', 'CEBALLOS');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('17', '162', 'PLAN DE AYALA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('18', '163', 'LA CUCHILLA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('19', '14', 'PANÚCO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('20', '22', 'PUENTE ALVARADO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('21', '33', 'NAUTLA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('22', '43', 'PUENTE TECOLUTLA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('23', '45', 'FORTIN');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('24', '49', 'TAMPICO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('25', '112', 'TAMPICO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('26', '116', 'CUITLAHUAC');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('27', '117', 'PASO DEL TORO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('28', '177', 'TOTOMOXTLE');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('29', '20', 'MATAMOROS');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('30', '30', 'PUENTE CAMARGO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('31', '37', 'REYNOSA SAN FERNANDO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('32', '48', 'SAN JUAN');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('33', '10', 'CULIACAN');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('34', '11', 'SINALOA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('35', '53', 'COMPOSTELA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('36', '86', 'SAN JOSE DEL CABO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('37', '95', 'DURANGO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('38', '96', 'LLANO GRANDE');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('39', '97', 'COSCOMATE');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('40', '98', 'MESILLAS');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('41', '195', 'AEROPUERTO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('42', '196', 'SAN LUCAS');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('43', '197', 'EL MANGLE');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('44', '5', 'PALMILLAS');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('45', '6', 'QUERETARO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('46', '41', 'SALAMANCA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('47', '42', 'LA PIEDAD');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('48', '87', 'ZACATECAS');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('49', '127', 'CHICHIMEQUILLAS');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('50', '183', 'VILLAGRAN');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('51', '186', 'CERRO GORDO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('52', '190', 'LAGOS DE MORENO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('53', '1', 'TLALPAN');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('54', '1', 'TRES MARIAS');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('55', '3', 'IGUALA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('56', '24', 'TEPOZTLÁN');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('57', '25', 'OACALCO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('58', '56', 'TAXCO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('59', '59', 'OAXTEPEC');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('60', '101', 'ALPUYECA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('61', '102', 'PASO MORELOS');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('62', '103', 'PALO BLANCO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('63', '104', 'LA VENTA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('64', '105', 'XOCHITEPEC');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('65', '107', 'EMILIANO ZAPATA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('66', '184', 'ING. FRANCISCO VELASCO DURÁN');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('67', '192', 'OZUMBA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('68', '193', 'LIBRAMIENTO CUERNAVACA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('69', '7', 'SAN MARCOS');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('70', '8', 'SAN MARTIN');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('71', '26', 'AMOZOC');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('72', '27', 'ESPERANZA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('73', '71', 'CHALCO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('74', '76', 'TEHUACAN');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('75', '77', 'MIAHUATLAN');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('76', '78', 'SUCHIXTLAHUACA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('77', '79', 'HUITZO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('78', '191', 'IXTAPALUCA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('79', '29', 'PUENTE CARACOL');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('80', '67', 'PUENTE NACIONAL ANTONIO DOVALI JAIME');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('81', '89', 'TEHUANTEPEC');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('82', '90', 'IXTEPEC');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('83', '118', 'COSAMALOAPAN');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('84', '119', 'ACAYUCAN - SAYULA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('85', '4', 'TEPOTZOTLAN');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('86', '69', 'JOROBAS');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('87', '70', 'POLOTITLAN');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('88', '133', 'CHAMAPA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('89', '135', 'NOPALA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('90', '136', 'MADIN');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('91', '137', 'ATIZAPAN');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('92', '138', 'LAGO DE GUADALUPE');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('93', '139', 'LECHERÍA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('94', '185', 'LOMAS VERDES');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('95', '38', 'PUENTE GRIJALVA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('96', '39', 'PUENTE USUMACINTA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('97', '132', 'SEYBAPLAYA');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('98', '164', 'PUENTE EL ZACATAL');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('99', '176', 'SANCHEZ MAGALLANES (AGUADULCE )');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('100', '179', 'LAS CHOAPAS');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('101', '181', 'MALPASITO');
INSERT INTO tableName (ID, NUMERO_CASETA, NOMBRE_CASETA) VALUES ('102', '182', 'OCOZOCOAUTLA (OCUILAPA)');

CREATE TABLE siniestro
(
    ID PRIMARY KEY AUTO_INCREMENT,
    SINIESTRO	INT,
    ID_TRAMO	INT,
    ID_CASETA	INT,
    FOREIGN KEY (ID_CASETA) REFERENCES CASETA(ID),
    FOREIGN KEY (ID_TRAMO) REFERENCES TRAMO(ID)
);

